default: &default
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: root
  password: development

development:
  <<: *default
  database: postgres_db_development

test:
  <<: *default
  database: postgres_db_test

production:
  <<: *default
  database: postgres_db_production
